<<<<<<< HEAD
{{- if .Values.hiera.hieradataurl }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: r10k-hiera-deploy
=======
{{- if .Values.puppetserver.puppeturl }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
<<<<<<< HEAD:templates/r10k-code-cronjob.yaml
  name: r10k-code-deploy
=======
  name: r10k-hiera-deploy
>>>>>>> create seperate r10k jobs/etc for code and hiera:templates/r10k-hiera-cronjob.yaml
>>>>>>> create seperate r10k jobs/etc for code and hiera
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "puppetserver.r10k.matchLabels" . | nindent 6 }}
<<<<<<< HEAD
  schedule: "{{.Values.r10k.hiera.cronJob.schedule}}"
=======
<<<<<<< HEAD:templates/r10k-code-cronjob.yaml
  schedule: "{{.Values.r10k.code.cronJob.schedule}}"
=======
  schedule: "{{.Values.r10k.hiera.cronJob.schedule}}"
>>>>>>> create seperate r10k jobs/etc for code and hiera:templates/r10k-hiera-cronjob.yaml
>>>>>>> create seperate r10k jobs/etc for code and hiera
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "puppetserver.r10k.labels" . | nindent 12 }}
          {{- if .Values.podAnnotations }}
          annotations:
            {{- toYaml .Values.podAnnotations | nindent 12 }}
          {{- end }}
        spec:
          containers:
<<<<<<< HEAD
            - name: r10k
              image: "{{.Values.r10k.image}}:{{.Values.r10k.tag}}"
              imagePullPolicy: "{{.Values.r10k.pullPolicy}}"
              resources:
                {{- toYaml .Values.r10k.hiera.resources | nindent 16 }}
              env:
                {{- range $key, $value := .Values.r10k.hiera.extraEnv }}
=======
            - name: r10k-code
              image: "{{.Values.r10k.image}}:{{.Values.r10k.tag}}"
              imagePullPolicy: "{{.Values.r10k.pullPolicy}}"
              resources:
<<<<<<< HEAD:templates/r10k-code-cronjob.yaml
                {{- toYaml .Values.r10k.code.resources | nindent 16 }}
              env:
                {{- range $key, $value := .Values.r10k.code.extraEnv }}
=======
                {{- toYaml .Values.r10k.hiera.resources | nindent 16 }}
              env:
                {{- range $key, $value := .Values.r10k.hiera.extraEnv }}
>>>>>>> create seperate r10k jobs/etc for code and hiera:templates/r10k-hiera-cronjob.yaml
>>>>>>> create seperate r10k jobs/etc for code and hiera
                - name: {{ $key }}
                  value: {{ $value }}
                {{- end }}
              args:
                - deploy
                - environment
                - --config
                - /etc/puppetlabs/puppet/r10k.yaml
                - --puppetfile
<<<<<<< HEAD
                {{- range $key, $value := .Values.r10k.hiera.extraArgs }}
=======
<<<<<<< HEAD:templates/r10k-code-cronjob.yaml
                {{- range $key, $value := .Values.r10k.code.extraArgs }}
=======
                {{- range $key, $value := .Values.r10k.hiera.extraArgs }}
>>>>>>> create seperate r10k jobs/etc for code and hiera:templates/r10k-hiera-cronjob.yaml
>>>>>>> create seperate r10k jobs/etc for code and hiera
                - {{ $value }}
                {{- end }}
              volumeMounts:
                {{- if and (.Values.r10k.viaSsh.credentials.ssh.value) (.Values.r10k.viaSsh.credentials.known_hosts.value) }}
                - name: r10k-secret
                  mountPath: /root/.ssh
                {{- end }}
                - name: r10k-volume
                  mountPath: /etc/puppetlabs/puppet/r10k.yaml
                  subPath: r10k.yaml
                - name: puppet-code-storage
                  mountPath: /etc/puppetlabs/code/
                - name: r10k-cache-storage
                  mountPath: /var/tmp/r10k_cache/
          restartPolicy: OnFailure
          volumes:
            - name: puppet-code-storage
              persistentVolumeClaim:
                claimName: puppet-code-claim
            - name: r10k-volume
              configMap:
<<<<<<< HEAD
                name: r10k-hiera-config
=======
<<<<<<< HEAD:templates/r10k-code-cronjob.yaml
                name: r10k-code-config
=======
                name: r10k-hiera-config
>>>>>>> create seperate r10k jobs/etc for code and hiera:templates/r10k-hiera-cronjob.yaml
>>>>>>> create seperate r10k jobs/etc for code and hiera
            - name: r10k-cache-storage
              persistentVolumeClaim:
                claimName: r10k-cache-claim
            {{- if and (.Values.r10k.viaSsh.credentials.ssh.value) (.Values.r10k.viaSsh.credentials.known_hosts.value) }}
            - name: r10k-secret
              secret:
                secretName: {{ template "r10k.secret" . }}
                defaultMode: 288 # = mode 0440
            {{- end }}
          {{- if (or (.Values.nodeSelector.allPods) (.Values.nodeSelector.commonStoragePods)) }}
          nodeSelector:
          {{- if (.Values.nodeSelector.allPods) }}
            {{ toYaml .Values.nodeSelector.allPods | nindent 14 }}
          {{- end }}
          {{- if (.Values.nodeSelector.commonStoragePods) }}
            {{ toYaml .Values.nodeSelector.commonStoragePods | nindent 14 }}
          {{- end }}
          {{- end }}
          {{- if .Values.affinity }}
          affinity:
            {{ toYaml .Values.affinity | nindent 14 }}
          {{- end }}
          {{- if .Values.tolerations }}
          tolerations:
            {{ toYaml .Values.tolerations| nindent 14 }}
          {{- end }}
          {{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") (.Values.priorityClassName) }}
          priorityClassName: {{ .Values.priorityClassName }}
          {{- end }}
{{- end }}
