apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: r10k-cache-claim
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
