{{- if .Values.hiera.hieradataurl }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: r10k-hiera-deploy
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "puppetserver.r10k.matchLabels" . | nindent 6 }}
  {{- with .Values.r10k.hiera.cronJob }}
  schedule: "{{.schedule}}"
  {{- if .concurrencyPolicy }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  {{- end }}
  {{- if .startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .startingDeadlineSeconds }}
  {{- end }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "puppetserver.r10k.labels" . | nindent 12 }}
          {{- if .Values.podAnnotations }}
          annotations:
            {{- toYaml .Values.podAnnotations | nindent 12 }}
          {{- end }}
        spec:
          containers:

            - name: r10k-hiera
              image: "{{.Values.r10k.image}}:{{.Values.r10k.tag}}"
              imagePullPolicy: "{{.Values.r10k.pullPolicy}}"
              resources:
                {{- toYaml .Values.r10k.hiera.resources | nindent 16 }}
              env:
                {{- range $key, $value := .Values.r10k.hiera.extraEnv }}
                - name: {{ $key }}
                  value: {{ $value }}
                {{- end }}
              args:
                - deploy
                - environment
                - --config
                - /etc/puppetlabs/puppet/r10k.yaml
                - --puppetfile
                {{- range $key, $value := .Values.r10k.hiera.extraArgs }}
                - {{ $value }}
                {{- end }}
              volumeMounts:
                {{- with .Values.r10k.hiera.viaSsh.credentials }}
                {{- if or (.existingSecret) (and (.ssh.value) (.known_hosts.value)) }}
                - name: r10k-hiera-secret
                  mountPath: /root/.ssh
                {{- end }}
                {{- end }}
                - name: r10k-volume
                  mountPath: /etc/puppetlabs/puppet/r10k.yaml
                  subPath: r10k.yaml
                - name: puppet-code-storage
                  mountPath: /etc/puppetlabs/code/
                - name: r10k-cache-storage
                  mountPath: /var/tmp/r10k_cache/
          {{- with .Values.r10k.hiera.cronJob }}
          {{- if .restartPolicy }}
          restartPolicy: {{ .restartPolicy }}
          {{- end }}
          {{- if .activeDeadlineSeconds }}
          activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
          {{- end }}
          {{- end }}
          volumes:
            - name: puppet-code-storage
              persistentVolumeClaim:
                claimName: puppet-code-claim
            - name: r10k-volume
              configMap:
                name: r10k-hiera-config
            - name: r10k-cache-storage
              persistentVolumeClaim:
                claimName: r10k-cache-claim
            {{- if or (.Values.r10k.hiera.viaSsh.credentials.existingSecret) (and (.Values.r10k.hiera.viaSsh.credentials.ssh.value) (.Values.r10k.hiera.viaSsh.credentials.known_hosts.value)) }}
            - name: r10k-hiera-secret
              secret:
                secretName: {{ template "r10k.hiera.secret" . }}
                defaultMode: 288 # = mode 0440
            {{- end }}
          {{- if (or (.Values.nodeSelector.allPods) (.Values.nodeSelector.commonStoragePods)) }}
          nodeSelector:
          {{- if (.Values.nodeSelector.allPods) }}
            {{ toYaml .Values.nodeSelector.allPods | nindent 14 }}
          {{- end }}
          {{- if (.Values.nodeSelector.commonStoragePods) }}
            {{ toYaml .Values.nodeSelector.commonStoragePods | nindent 14 }}
          {{- end }}
          {{- end }}
          {{- if .Values.affinity }}
          affinity:
            {{ toYaml .Values.affinity | nindent 14 }}
          {{- end }}
          {{- if .Values.tolerations }}
          tolerations:
            {{ toYaml .Values.tolerations| nindent 14 }}
          {{- end }}
          {{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") (.Values.priorityClassName) }}
          priorityClassName: {{ .Values.priorityClassName }}
          {{- end }}
{{- end }}
